name:
  Continuous Integration, Continuous Delivery Pipeline (GitHub Container Registry)

on:
  push:
    tags:
      - "v*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd frontend && pnpm install

  build:
    needs: install
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd frontend && pnpm install

      - name: Run Type Checking
        run: cd frontend && pnpm run type-check

      - name: Run Build
        run: cd frontend && pnpm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sofia_diet:latest

      - name: Add Deployment Link to UI
        run:
          echo "🔗 [View your deployment here](https://github.com/${{
          github.actor}}/sofia_diet/pkgs/container/sofia_diet/versions)" >>
          $GITHUB_STEP_SUMMARY
