name: Continuous Integration, Continuous Delivery Pipeline (Docker Hub)

on:
  push:
    tags:
      - "v*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Move to the project directory
        run: cd frontend

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install library dependencies
        run: cd lib && pnpm install

      - name: Install dependencies
        run: cd frontend && pnpm install

  build:
    needs: install
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install library dependencies
        run: cd lib && pnpm install

      - name: Install dependencies
        run: cd frontend && pnpm install

      - name: Run Type Checking
        run: cd frontend && pnpm run type-check

      - name: Run Build
        run: cd frontend && pnpm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sofia_diet:latest
